[project]
name = "day3"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.123.4",
    "python-multipart>=0.0.20",
    "uvicorn>=0.38.0",
]
